# Generated by Django 5.2.5 on 2025-08-28 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='文件ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_name', models.CharField(max_length=255, verbose_name='存储文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('uploaded_by', models.CharField(max_length=32, verbose_name='上传用户ID')),
                ('upload_ip', models.GenericIPAddressField(verbose_name='上传IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
                'db_table': 'tx_file_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('business', '业务配置'), ('ui', '界面配置')], default='system', max_length=20, verbose_name='配置类型')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'tx_system_configs',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('category_type', models.CharField(choices=[('product', '产品分类'), ('service', '服务分类'), ('industry', '行业分类')], max_length=20, verbose_name='分类类型')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'tx_categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='地区代码')),
                ('name', models.CharField(max_length=50, verbose_name='地区名称')),
                ('level', models.CharField(choices=[('province', '省份'), ('city', '城市'), ('district', '区县')], max_length=20, verbose_name='级别')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region', verbose_name='上级地区')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'tx_regions',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
