# Generated by Django 5.2.5 on 2025-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "正常"),
                    ("inactive", "未激活"),
                    ("pending_review", "待审核"),
                    ("banned", "已封禁"),
                ],
                default="active",
                max_length=20,
                verbose_name="用户状态",
            ),
        ),
    ]
