# Generated by Django 5.2.5 on 2025-08-29 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='权限ID')),
                ('perm_code', models.CharField(max_length=100, unique=True, verbose_name='权限标识')),
                ('perm_name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('module', models.CharField(max_length=50, verbose_name='所属模块')),
                ('function', models.CharField(max_length=50, verbose_name='所属功能')),
                ('action', models.CharField(choices=[('view', '查看'), ('create', '新增'), ('edit', '编辑'), ('delete', '删除'), ('audit', '审核'), ('export', '导出'), ('import', '导入')], max_length=20, verbose_name='操作类型')),
                ('is_api', models.BooleanField(default=True, verbose_name='是否接口权限')),
                ('api_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='接口路径')),
                ('api_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='接口方法')),
                ('description', models.TextField(blank=True, null=True, verbose_name='权限描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'tx_permissions',
                'ordering': ['module', 'function', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='角色ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'tx_roles',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('security', '安全配置'), ('ui', '界面配置'), ('business', '业务配置')], default='system', max_length=20, verbose_name='配置类型')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'tx_org_system_configs',
                'ordering': ['config_type', 'config_key'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('operation', models.CharField(max_length=100, verbose_name='操作内容')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('ip_address', models.GenericIPAddressField(verbose_name='操作IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_result', models.BooleanField(verbose_name='操作结果')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'tx_operation_logs',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('parent_id', models.UUIDField(blank=True, null=True, verbose_name='父菜单ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='前端组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序号')),
                ('terminal', models.CharField(choices=[('pc', '电脑端'), ('mobile', '移动端')], default='pc', max_length=10, verbose_name='终端类型')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外部链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='organization.permission', verbose_name='关联权限')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tx_menus',
                'ordering': ['sort', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单',
                'verbose_name_plural': '角色菜单',
                'db_table': 'tx_role_menus',
                'unique_together': {('role', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'tx_role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'tx_user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
